### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by ghost** [MrBenFTW/C0F3-IPA#1]
i have an iphone 6s (ios 10.3.3). i click allow and the app just crashes.

**Comment by Ankiiii** [comment]
I have the same exact issue but I am on iOS 10.3.2.

**Comment by Cwoodyard** [comment]
try this ipa: https://github.com/MrBenFTW/C0F3-IPA/blob/master/C0F3(IOS10).ipa

**Comment by ghost** [comment]
that's the same ipa i've used. it's crashing over, and over again. i've rebooted multiple times as well.

**Comment by iambenmitchell** [comment]
V0rtex requires multiple tries. A update that will make it more stable is coming but in the mean time keep trying
