### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AriDuski** [MrBenFTW/C0F3-IPA#2]
i'm on ios 10.2.3 iphone 6 , but it's not working in my device

**Comment by Cwoodyard** [comment]
make sure that you are downloading the right one for your ios. It sounds like you have the wrong app. download the IPA here: https://github.com/MrBenFTW/C0F3-IPA/blob/master/C0F3(IOS10).ipa

**Comment by BABAbai13c** [comment]
iphone 6 10.3.1...not wrking..after press Allow it still on same status JailBreak need absolute Silence! ...after wait til 10 mins i stops C0F3 app by multitasking and phon restarts....nothing new installed 😪

**Comment by iambenmitchell** [comment]
V0rtex requires multiple tries. A update that will make it more stable is coming but in the mean time keep trying
