### ISSUE TITLE
Cydia Can't Open

### ISSUE THREAD

**Issue by SK-sep** [MrBenFTW/C0F3-IPA#5]
Cydia Can't open in IOS 11.1.2
when i tap cydia to open, cydia automaticaly close

**Comment by iambenmitchell** [comment]
Sometimes it works sometimes it does not

On my iPhone X 11.1.2 it works fine! but on my friends iPhone 7 plus 11.1.2 it does not
Cydia is useless anyways with out a update by Saurik
