### ISSUE TITLE
10.3.3 5s

### ISSUE THREAD

**Issue by hiimtt2k3** [MrBenFTW/C0F3-IPA#6]
i clicked an ALLOW AND ITS JUST STUCK THERE
CANT DO ANYTHING MORE
PLEASE CHECK AGAIN......... 
and i have a question that 
does saurik update the CYDIA SUBTRATE A;READY ?+

**Comment by iambenmitchell** [comment]
V0rtex requires multiple tries. A update that will make it more stable is coming but in the mean time keep trying

And Saurik has not updated Cydia
